# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='org.seekloud.theia.faceAnalysis.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\"org.seekloud.theia.faceAnalysis.pb\"L\n\x07ImgData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x14\n\x0cpixel_length\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"S\n\x08ImageReq\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12\x38\n\x03img\x18\x02 \x01(\x0b\x32+.org.seekloud.theia.faceAnalysis.pb.ImgData\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"<\n\x04Mask\x12\x34\n\x01p\x18\x01 \x03(\x0b\x32).org.seekloud.theia.faceAnalysis.pb.Point\"M\n\x07MarkRsp\x12\r\n\x05\x66rame\x18\x01 \x01(\x05\x12\x33\n\x01l\x18\x02 \x03(\x0b\x32(.org.seekloud.theia.faceAnalysis.pb.Maskb\x06proto3')
)




_IMGDATA = _descriptor.Descriptor(
  name='ImgData',
  full_name='org.seekloud.theia.faceAnalysis.pb.ImgData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='org.seekloud.theia.faceAnalysis.pb.ImgData.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='org.seekloud.theia.faceAnalysis.pb.ImgData.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_length', full_name='org.seekloud.theia.faceAnalysis.pb.ImgData.pixel_length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='org.seekloud.theia.faceAnalysis.pb.ImgData.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=125,
)


_IMAGEREQ = _descriptor.Descriptor(
  name='ImageReq',
  full_name='org.seekloud.theia.faceAnalysis.pb.ImageReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='org.seekloud.theia.faceAnalysis.pb.ImageReq.frame', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='img', full_name='org.seekloud.theia.faceAnalysis.pb.ImageReq.img', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=210,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='org.seekloud.theia.faceAnalysis.pb.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='org.seekloud.theia.faceAnalysis.pb.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='org.seekloud.theia.faceAnalysis.pb.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=241,
)


_MASK = _descriptor.Descriptor(
  name='Mask',
  full_name='org.seekloud.theia.faceAnalysis.pb.Mask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='org.seekloud.theia.faceAnalysis.pb.Mask.p', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=303,
)


_MARKRSP = _descriptor.Descriptor(
  name='MarkRsp',
  full_name='org.seekloud.theia.faceAnalysis.pb.MarkRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='org.seekloud.theia.faceAnalysis.pb.MarkRsp.frame', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='l', full_name='org.seekloud.theia.faceAnalysis.pb.MarkRsp.l', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=382,
)

_IMAGEREQ.fields_by_name['img'].message_type = _IMGDATA
_MASK.fields_by_name['p'].message_type = _POINT
_MARKRSP.fields_by_name['l'].message_type = _MASK
DESCRIPTOR.message_types_by_name['ImgData'] = _IMGDATA
DESCRIPTOR.message_types_by_name['ImageReq'] = _IMAGEREQ
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Mask'] = _MASK
DESCRIPTOR.message_types_by_name['MarkRsp'] = _MARKRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgData = _reflection.GeneratedProtocolMessageType('ImgData', (_message.Message,), {
  'DESCRIPTOR' : _IMGDATA,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.theia.faceAnalysis.pb.ImgData)
  })
_sym_db.RegisterMessage(ImgData)

ImageReq = _reflection.GeneratedProtocolMessageType('ImageReq', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQ,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.theia.faceAnalysis.pb.ImageReq)
  })
_sym_db.RegisterMessage(ImageReq)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.theia.faceAnalysis.pb.Point)
  })
_sym_db.RegisterMessage(Point)

Mask = _reflection.GeneratedProtocolMessageType('Mask', (_message.Message,), {
  'DESCRIPTOR' : _MASK,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.theia.faceAnalysis.pb.Mask)
  })
_sym_db.RegisterMessage(Mask)

MarkRsp = _reflection.GeneratedProtocolMessageType('MarkRsp', (_message.Message,), {
  'DESCRIPTOR' : _MARKRSP,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:org.seekloud.theia.faceAnalysis.pb.MarkRsp)
  })
_sym_db.RegisterMessage(MarkRsp)


# @@protoc_insertion_point(module_scope)
