# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lib.protos.genpy.api_pb2 as api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='org.seekloud.theia.faceAnalysis.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rservice.proto\x12\"org.seekloud.theia.faceAnalysis.pb\x1a\tapi.proto2r\n\nFaceServer\x12\x64\n\x07predict\x12,.org.seekloud.theia.faceAnalysis.pb.ImageReq\x1a+.org.seekloud.theia.faceAnalysis.pb.MarkRspb\x06proto3')
  ,
  dependencies=[api__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FACESERVER = _descriptor.ServiceDescriptor(
  name='FaceServer',
  full_name='org.seekloud.theia.faceAnalysis.pb.FaceServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=64,
  serialized_end=178,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='org.seekloud.theia.faceAnalysis.pb.FaceServer.predict',
    index=0,
    containing_service=None,
    input_type=api__pb2._IMAGEREQ,
    output_type=api__pb2._MARKRSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACESERVER)

DESCRIPTOR.services_by_name['FaceServer'] = _FACESERVER

# @@protoc_insertion_point(module_scope)
